dist: xenial
sudo: false

language: node_js
node_js: '10'

env:
  global:
   - DIR=/home/travis/build/aeternity/aepp-graffiti

jobs:
  include:
    - stage: aepp
      script: 
       - cd $DIR/aepp
       - npm install
       - npm run build
    - stage: server
      script:
       - cd $DIR/server
       - docker build -t dronegraffiti/server .
    - stage: contract
      script:
       - cd $DIR/contract
       - npm install -g forgae
       - npm install
       - forgae node
       - forgae test

