version: '3'
services:

  aeternity:
    image: "aeternity/epoch:latest"
    command: "-aehttp enable_debug_endpoints true"
    volumes:
      - "./node-server/docker/epoch.yaml:/home/epoch/.epoch/epoch/epoch.yaml"
      - "./node-server/docker/aeternity_uat:/home/epoch/node/data/mnesia"
    ports:
      - "3013:3013"
      - "3113:3113"

  aeternity-proxy:
    image: nginx:latest
    ports:
      - "3001:3001"
    volumes:
      - ./aeternity-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - "aeternity"

  ipfs:
    image: "ipfs/go-ipfs:latest"
    volumes:
      - ./node-server/docker/ipfs:/data/ipfs
    ports:
      - "4001:4001"
      - "4001:4002/udp"
      - "5001:5001"

  server:
    build: node-server
    restart: on-failure
    environment:
      - IPFS_URL=ipfs
      - AETERNITY_URL=aeternity
    depends_on: 
      - "aeternity"
      - "ipfs"
    links:
      - "aeternity"
      - "ipfs"
    volumes:
      - "./node-server/docker/rendered:/app/rendered"
      
  server-proxy:
    image: nginx:latest
    ports:
      - "3002:3002"
    volumes:
      - ./node-server/docker/rendered:/usr/share/nginx/html/rendered
      - ./server-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server-nginx-cors.conf:/etc/nginx/cors.conf
    depends_on: 
      - "server"

  base-aepp:
    build:
      context: .
      dockerfile: Dockerfile.base-aepp
    ports:
      - "8084:80"
      
  aepp:
    build: aepp
    depends_on: 
      - "server"
      - "base-aepp"
    ports:
      - "8085:80"
