version: '3'
services:

  aeternity:
    image: aeternity/aeternity:latest
    command: "-aehttp enable_debug_endpoints true"
    environment:
      - EPOCH_CONFIG=/home/aeternity/aeternity.yaml
    volumes:
      - ./aeternity.yaml:/home/aeternity/aeternity.yaml
      - ./.docker/aeternity_uat:/home/aeternity/node/data/mnesia
    ports:
      - "3013:3013"
      - "3113:3113"

  aeternity-proxy:
    image: nginx:latest
    ports:
      - "3001:3001"
    volumes:
      - ./aeternity-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - "aeternity"

  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
      - ./.docker/ipfs:/data/ipfs
    ports:
      - "4001:4001"
      - "4001:4002/udp"
      - "5001:5001"

  server:
    image: dronegraffiti/server:latest
    restart: on-failure
    environment:
      - IPFS_URL=ipfs
      - AETERNITY_URL=aeternity
      - S3_KEY=access-key
      - S3_SECRET=secret-key
      - S3_REGION=bucket-name
      - S3_BUCKET=region-code
    depends_on: 
      - "aeternity"
      - "ipfs"
    links:
      - "aeternity"
      - "ipfs"
    volumes:
      - "./.docker/rendered:/app/data/rendered"
      - "./.docker/backup:/app/data/backup"
      
  server-proxy:
    image: nginx:latest
    ports:
      - "3002:3002"
    volumes:
      - ./.docker/rendered:/usr/share/nginx/html/rendered
      - ./server-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server-nginx-cors.conf:/etc/nginx/cors.conf
    depends_on: 
      - "server"

  base-aepp:
    image: dronegraffiti/demo-base-aepp:latest
    ports:
      - "8084:80"
      
  aepp:
    image: dronegraffiti/aepp:latest
    depends_on: 
      - "server"
      - "base-aepp"
    ports:
      - "8085:80"
      
  matomo:
    image: crazymax/matomo:latest
    container_name: matomo
    volumes:
      - "./.docker/tracking/matomo:/data"
    depends_on:
      - matomo_database
    ports:
      - "8000:8000"

  matomo_database:
    image: mariadb:latest
    container_name: matomo_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=matomo_db
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=matomo
    volumes:
      - './.docker/tracking/mysql:/var/lib/mysql'

